version: '3.4'

services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6384:6379
    environment:
      - REDIS_REPLICATION_MODE=master

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
