network: testnet
urls:
  api: 'https://testnet-api.multiversx.com'
  gateway: 'https://testnet-gateway.multiversx.com'
  elastic: 'https://testnet-index.multiversx.com'
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
api:
  port: 3000
  prefix: 'liquid-staking-aggregator'
flags:
  useKeepAliveAgent: true
testConfig:
  acceptablePercentageDifference: 10
  apiSleepTime: 10000
  batchApiRequestSize: 10
